// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Build", "CA1303:Method 'void FeedbackService.processColorIcon(ColorFeedback c)' passes a literal string as parameter 'message' of a call to 'void MessagingCenter.Send<FeedbackService, Bundle>(FeedbackService sender, string message, Bundle args)'. Retrieve the following string(s) from a resource table instead: \"ReceiveIconSettings\".", Justification = "<Pending>", Scope = "member", Target = "~M:SensorFeedbackWF.Services.FeedbackService.processColorIcon(SensorFeedbackWF.Services.FeedbackService.ColorFeedback)")]
[assembly: SuppressMessage("Build", "CA1304:The behavior of 'string.ToLower()' could vary based on the current user's locale settings. Replace this call in 'FeedbackService.processColorNotification(FeedbackService.ColorFeedback)' with a call to 'string.ToLower(CultureInfo)'.", Justification = "<Pending>", Scope = "member", Target = "~M:SensorFeedbackWF.Services.FeedbackService.ProcessColorNotification(SensorFeedbackWF.Services.FeedbackService.ColorFeedback)")]
[assembly: SuppressMessage("Build", "CA1303:Method 'void FeedbackService.processColorRing(ColorFeedback c)' passes a literal string as parameter 'message' of a call to 'void MessagingCenter.Send<FeedbackService, Bundle>(FeedbackService sender, string message, Bundle args)'. Retrieve the following string(s) from a resource table instead: \"ReceiveRingSettings\".", Justification = "<Pending>", Scope = "member", Target = "~M:SensorFeedbackWF.Services.FeedbackService.ProcessColorRing(SensorFeedbackWF.Services.FeedbackService.ColorFeedback)")]
[assembly: SuppressMessage("Build", "CA1303:Method 'MainPage.MainPage()' passes a literal string as parameter 'message' of a call to 'void MessagingCenter.Subscribe<FeedbackService, string>(object subscriber, string message, Action<FeedbackService, string> callback, FeedbackService source = null)'. Retrieve the following string(s) from a resource table instead: \"printMe\".", Justification = "<Pending>", Scope = "member", Target = "~M:SensorFeedbackWF.Views.MainPage.#ctor")]
[assembly: SuppressMessage("Build", "CA1507:Use nameof in place of string literal 'message'", Justification = "<Pending>", Scope = "member", Target = "~M:SensorFeedbackWF.Views.MainPage.ReceiveIconSettings(Tizen.Applications.Bundle)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Build", "CA1303:Method 'Task MainPage.ReceiveRingSettings(Bundle message)' passes a literal string as parameter 'value' of a call to 'void Label.Text.set'. Retrieve the following string(s) from a resource table instead: \"FailedRingSettings\".", Justification = "<Pending>", Scope = "member", Target = "~M:SensorFeedbackWF.Views.MainPage.ReceiveRingSettings(Tizen.Applications.Bundle)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Build", "CA1507:Use nameof in place of string literal 'message'", Justification = "<Pending>", Scope = "member", Target = "~M:SensorFeedbackWF.Views.MainPage.ReceiveRingSettings(Tizen.Applications.Bundle)~System.Threading.Tasks.Task")]
